spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "GET,POST,PUT,DELETE,OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: users-route
          uri: lb://users
          predicates:
            - Path=/users/*
        - id: clients-route
          uri: lb://client
          predicates:
            - Path=/clients/**
        - id: notifications-route
          uri: lb://notifications
          predicates:
            - Path=/notifications/**