spring:
  cloud:
    gateway:

      # Explicit route definitions for each microservice:
      routes:

        # Route for the Users service
        - id: users-route
          uri: lb://users
          predicates:
            - Path=/users/**

        # Route for the Clients service
        - id: clients-route
          uri: lb://client
          predicates:
            - Path=/clients/**

        # Route for the Notifications service
        - id: notifications-route
          uri: lb://notifications
          predicates:
            - Path=/notifications/**
